import {
  AuthAccessReadScope,
  AuthOrchestrationOperateScope,
  AuthOrchestrationReadScope,
  AuthRelayReadScope,
  AuthRelayWriteScope,
  AuthReviewWriteScope,
  AuthTerminalOperateScope,
  ORCHESTRATION_WS_METHODS,
  type AuthEnvironmentScope,
  WS_METHODS,
  WsRpcGroup,
} from "@t3tools/contracts";
import type * as RpcGroup from "effect/unstable/rpc/RpcGroup";

type WsRpcMethod = RpcGroup.Rpcs<typeof WsRpcGroup>["_tag"];

/**
 * Keep authorization coverage coupled to the RPC group itself. Adding an RPC to
 * `WsRpcGroup` without choosing a scope is a type error instead of a production
 * runtime failure.
 */
export const RPC_REQUIRED_SCOPES = {
  [ORCHESTRATION_WS_METHODS.dispatchCommand]: AuthOrchestrationOperateScope,
  [ORCHESTRATION_WS_METHODS.getTurnDiff]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.getFullThreadDiff]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.searchThreads]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.subscribeShell]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.getArchivedShellSnapshot]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.subscribeThread]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.subscribeMissions]: AuthOrchestrationReadScope,
  [ORCHESTRATION_WS_METHODS.subscribeMission]: AuthOrchestrationReadScope,
  [WS_METHODS.serverProbe]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetConfig]: AuthOrchestrationReadScope,
  [WS_METHODS.serverRefreshProviders]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpdateProvider]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpdateServer]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpdateServerWithProgress]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverUpsertKeybinding]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverRemoveKeybinding]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverGetSettings]: AuthOrchestrationReadScope,
  [WS_METHODS.serverUpdateSettings]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverDiscoverSourceControl]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetTraceDiagnostics]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetProcessDiagnostics]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetProcessResourceHistory]: AuthOrchestrationReadScope,
  [WS_METHODS.serverGetResourceTelemetryHistory]: AuthOrchestrationReadScope,
  [WS_METHODS.serverRetryResourceTelemetry]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverSignalProcess]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverReportClientActivity]: AuthOrchestrationReadScope,
  [WS_METHODS.serverReportHostPowerState]: AuthOrchestrationOperateScope,
  [WS_METHODS.serverGetBackgroundPolicy]: AuthOrchestrationReadScope,
  [WS_METHODS.cloudGetRelayClientStatus]: AuthRelayReadScope,
  [WS_METHODS.cloudInstallRelayClient]: AuthRelayWriteScope,
  [WS_METHODS.sourceControlLookupRepository]: AuthOrchestrationReadScope,
  [WS_METHODS.sourceControlCloneRepository]: AuthOrchestrationOperateScope,
  [WS_METHODS.sourceControlPublishRepository]: AuthOrchestrationOperateScope,
  [WS_METHODS.projectsListEntries]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsReadFile]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsSearchContents]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsSearchEntries]: AuthOrchestrationReadScope,
  [WS_METHODS.projectsWriteFile]: AuthOrchestrationOperateScope,
  [WS_METHODS.shellOpenInEditor]: AuthOrchestrationOperateScope,
  [WS_METHODS.filesystemBrowse]: AuthOrchestrationReadScope,
  [WS_METHODS.assetsCreateUrl]: AuthOrchestrationReadScope,
  [WS_METHODS.verificationGetProjectConfiguration]: AuthOrchestrationReadScope,
  [WS_METHODS.verificationListRuns]: AuthOrchestrationReadScope,
  [WS_METHODS.verificationGetRunEvidence]: AuthOrchestrationReadScope,
  [WS_METHODS.verificationGetTaskSummaries]: AuthOrchestrationReadScope,
  [WS_METHODS.verificationCompareRuns]: AuthOrchestrationReadScope,
  [WS_METHODS.verificationReadLog]: AuthOrchestrationReadScope,
  [WS_METHODS.verificationCreateArtifactUrl]: AuthOrchestrationReadScope,
  [WS_METHODS.verificationSubscribeRun]: AuthOrchestrationReadScope,
  [WS_METHODS.githubListAccounts]: AuthOrchestrationReadScope,
  [WS_METHODS.githubConnectAccount]: AuthOrchestrationOperateScope,
  [WS_METHODS.githubDisconnectAccount]: AuthOrchestrationOperateScope,
  [WS_METHODS.githubConnectRepository]: AuthOrchestrationOperateScope,
  [WS_METHODS.githubDisconnectRepository]: AuthOrchestrationOperateScope,
  [WS_METHODS.githubGetWorkspace]: AuthOrchestrationReadScope,
  [WS_METHODS.githubListIssues]: AuthOrchestrationReadScope,
  [WS_METHODS.githubListPullRequests]: AuthOrchestrationReadScope,
  [WS_METHODS.githubGetPullRequest]: AuthOrchestrationReadScope,
  [WS_METHODS.githubRefresh]: AuthOrchestrationOperateScope,
  [WS_METHODS.githubCreateMissionFromIssue]: AuthOrchestrationOperateScope,
  [WS_METHODS.githubLinkIssueMission]: AuthOrchestrationOperateScope,
  [WS_METHODS.githubCreateReviewTask]: AuthOrchestrationOperateScope,
  [WS_METHODS.githubPushBranch]: AuthOrchestrationOperateScope,
  [WS_METHODS.githubCreatePullRequest]: AuthOrchestrationOperateScope,
  [WS_METHODS.githubUpdatePullRequest]: AuthOrchestrationOperateScope,
  [WS_METHODS.githubMarkReadyForReview]: AuthOrchestrationOperateScope,
  [WS_METHODS.githubResolveReviewThread]: AuthReviewWriteScope,
  [WS_METHODS.githubSubscribeWorkspace]: AuthOrchestrationReadScope,
  [WS_METHODS.memoryGetWorkspace]: AuthOrchestrationReadScope,
  [WS_METHODS.memoryListEntries]: AuthOrchestrationReadScope,
  [WS_METHODS.memoryGetEntry]: AuthOrchestrationReadScope,
  [WS_METHODS.memoryCreateEntry]: AuthOrchestrationOperateScope,
  [WS_METHODS.memoryUpdateEntry]: AuthOrchestrationOperateScope,
  [WS_METHODS.memoryActionEntry]: AuthOrchestrationOperateScope,
  [WS_METHODS.memorySupersedeEntry]: AuthOrchestrationOperateScope,
  [WS_METHODS.memoryAddSource]: AuthOrchestrationOperateScope,
  [WS_METHODS.memoryCreateRelation]: AuthOrchestrationOperateScope,
  [WS_METHODS.memoryListProposals]: AuthOrchestrationReadScope,
  [WS_METHODS.memoryCreateProposal]: AuthOrchestrationOperateScope,
  [WS_METHODS.memoryReviewProposal]: AuthOrchestrationOperateScope,
  [WS_METHODS.memoryListIndexedSources]: AuthOrchestrationReadScope,
  [WS_METHODS.memoryRequestIndex]: AuthOrchestrationOperateScope,
  [WS_METHODS.memorySearch]: AuthOrchestrationReadScope,
  [WS_METHODS.memoryListRetrievals]: AuthOrchestrationReadScope,
  [WS_METHODS.memoryGetRetrieval]: AuthOrchestrationReadScope,
  [WS_METHODS.memoryUpdateSettings]: AuthOrchestrationOperateScope,
  [WS_METHODS.memoryExport]: AuthOrchestrationReadScope,
  [WS_METHODS.memoryImport]: AuthOrchestrationOperateScope,
  [WS_METHODS.memorySubscribeWorkspace]: AuthOrchestrationReadScope,
  [WS_METHODS.routingGetRegistry]: AuthOrchestrationReadScope,
  [WS_METHODS.routingGetWorkspace]: AuthOrchestrationReadScope,
  [WS_METHODS.routingGetDecision]: AuthOrchestrationReadScope,
  [WS_METHODS.routingListHistory]: AuthOrchestrationReadScope,
  [WS_METHODS.routingSimulate]: AuthOrchestrationOperateScope,
  [WS_METHODS.routingStartMission]: AuthOrchestrationOperateScope,
  [WS_METHODS.routingSavePolicy]: AuthOrchestrationOperateScope,
  [WS_METHODS.routingSaveRule]: AuthOrchestrationOperateScope,
  [WS_METHODS.routingSaveOverride]: AuthOrchestrationOperateScope,
  [WS_METHODS.routingRevokeOverride]: AuthOrchestrationOperateScope,
  [WS_METHODS.routingSaveAssessment]: AuthOrchestrationOperateScope,
  [WS_METHODS.routingSaveProviderProfile]: AuthOrchestrationOperateScope,
  [WS_METHODS.routingSaveModelProfile]: AuthOrchestrationOperateScope,
  [WS_METHODS.routingSaveCapabilitySnapshot]: AuthOrchestrationOperateScope,
  [WS_METHODS.routingRefreshRegistry]: AuthOrchestrationOperateScope,
  [WS_METHODS.routingSubscribeWorkspace]: AuthOrchestrationReadScope,
  [WS_METHODS.analyticsGetWorkspace]: AuthOrchestrationReadScope,
  [WS_METHODS.analyticsGetRunDetail]: AuthOrchestrationReadScope,
  [WS_METHODS.analyticsUpdateSettings]: AuthOrchestrationOperateScope,
  [WS_METHODS.analyticsSaveBudget]: AuthOrchestrationOperateScope,
  [WS_METHODS.analyticsSavePricingSnapshot]: AuthOrchestrationOperateScope,
  [WS_METHODS.analyticsSaveSubscriptionAttributionRule]: AuthOrchestrationOperateScope,
  [WS_METHODS.analyticsSaveExchangeRateSnapshot]: AuthOrchestrationOperateScope,
  [WS_METHODS.analyticsAcknowledgeBudgetEvent]: AuthOrchestrationOperateScope,
  [WS_METHODS.analyticsCreateBudgetOverride]: AuthOrchestrationOperateScope,
  [WS_METHODS.analyticsAcknowledgeAlert]: AuthOrchestrationOperateScope,
  [WS_METHODS.analyticsSaveAnnotation]: AuthOrchestrationOperateScope,
  [WS_METHODS.analyticsRecordHumanDisposition]: AuthOrchestrationOperateScope,
  [WS_METHODS.analyticsCreateExport]: AuthOrchestrationReadScope,
  [WS_METHODS.analyticsStartRetention]: AuthOrchestrationOperateScope,
  [WS_METHODS.analyticsRebuildAggregates]: AuthOrchestrationOperateScope,
  [WS_METHODS.analyticsSubscribeWorkspace]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeVcsStatus]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeResourceTelemetry]: AuthOrchestrationReadScope,
  [WS_METHODS.vcsRefreshStatus]: AuthOrchestrationReadScope,
  [WS_METHODS.vcsPull]: AuthOrchestrationOperateScope,
  [WS_METHODS.gitRunStackedAction]: AuthOrchestrationOperateScope,
  [WS_METHODS.gitResolvePullRequest]: AuthOrchestrationOperateScope,
  [WS_METHODS.gitPreparePullRequestThread]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsListRefs]: AuthOrchestrationReadScope,
  [WS_METHODS.vcsCreateWorktree]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsRemoveWorktree]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsCreateRef]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsSwitchRef]: AuthOrchestrationOperateScope,
  [WS_METHODS.vcsInit]: AuthOrchestrationOperateScope,
  [WS_METHODS.reviewGetDiffPreview]: AuthReviewWriteScope,
  [WS_METHODS.terminalOpen]: AuthTerminalOperateScope,
  [WS_METHODS.terminalAttach]: AuthTerminalOperateScope,
  [WS_METHODS.terminalWrite]: AuthTerminalOperateScope,
  [WS_METHODS.terminalResize]: AuthTerminalOperateScope,
  [WS_METHODS.terminalClear]: AuthTerminalOperateScope,
  [WS_METHODS.terminalRestart]: AuthTerminalOperateScope,
  [WS_METHODS.terminalClose]: AuthTerminalOperateScope,
  [WS_METHODS.subscribeTerminalEvents]: AuthTerminalOperateScope,
  [WS_METHODS.subscribeTerminalMetadata]: AuthTerminalOperateScope,
  [WS_METHODS.previewOpen]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewNavigate]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewResize]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewRefresh]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewClose]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewList]: AuthOrchestrationReadScope,
  [WS_METHODS.previewReportStatus]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewAutomationConnect]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewAutomationRespond]: AuthOrchestrationOperateScope,
  [WS_METHODS.previewAutomationFocusHost]: AuthOrchestrationOperateScope,
  [WS_METHODS.subscribePreviewEvents]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeDiscoveredLocalServers]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeServerConfig]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeServerLifecycle]: AuthOrchestrationReadScope,
  [WS_METHODS.subscribeAuthAccess]: AuthAccessReadScope,
  [WS_METHODS.subscribeBackgroundPolicy]: AuthOrchestrationReadScope,
} as const satisfies Readonly<Record<WsRpcMethod, AuthEnvironmentScope>>;

export function requiredScopeForRpcMethod(method: string): AuthEnvironmentScope {
  if (!Object.hasOwn(RPC_REQUIRED_SCOPES, method)) {
    throw new Error(`RPC method ${method} has no declared authorization scope.`);
  }
  const requiredScope = RPC_REQUIRED_SCOPES[method as WsRpcMethod];
  if (requiredScope === undefined) {
    throw new Error(`RPC method ${method} has no declared authorization scope.`);
  }
  return requiredScope;
}
