import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadSettledPayload as ContractsThreadSettledPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadUnsettledPayload as ContractsThreadUnsettledPayloadSchema,
  ThreadSnoozedPayload as ContractsThreadSnoozedPayloadSchema,
  ThreadUnsnoozedPayload as ContractsThreadUnsnoozedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  MissionCreatedPayload as ContractsMissionCreatedPayloadSchema,
  MissionUpdatedPayload as ContractsMissionUpdatedPayloadSchema,
  MissionStartedPayload as ContractsMissionStartedPayloadSchema,
  MissionCancellationRequestedPayload as ContractsMissionCancellationRequestedPayloadSchema,
  MissionCancelledPayload as ContractsMissionCancelledPayloadSchema,
  MissionCompletedPayload as ContractsMissionCompletedPayloadSchema,
  MissionFailedPayload as ContractsMissionFailedPayloadSchema,
  MissionRecoveryBlockedPayload as ContractsMissionRecoveryBlockedPayloadSchema,
  MissionTaskCreatedPayload as ContractsMissionTaskCreatedPayloadSchema,
  MissionTaskUpdatedPayload as ContractsMissionTaskUpdatedPayloadSchema,
  MissionTaskLifecyclePayload as ContractsMissionTaskLifecyclePayloadSchema,
  AgentRunStartedPayload as ContractsAgentRunStartedPayloadSchema,
  AgentRunLifecyclePayload as ContractsAgentRunLifecyclePayloadSchema,
  MissionTeamConfiguredPayload as ContractsMissionTeamConfiguredPayloadSchema,
  MissionAgentUpsertedPayload as ContractsMissionAgentUpsertedPayloadSchema,
  MissionAgentRemovedPayload as ContractsMissionAgentRemovedPayloadSchema,
  MissionAgentPermissionsUpdatedPayload as ContractsMissionAgentPermissionsUpdatedPayloadSchema,
  MissionTaskDependencyAddedPayload as ContractsMissionTaskDependencyAddedPayloadSchema,
  MissionTaskDependencyRemovedPayload as ContractsMissionTaskDependencyRemovedPayloadSchema,
  MissionTaskReadyPayload as ContractsMissionTaskReadyPayloadSchema,
  MissionTaskBlockedPayload as ContractsMissionTaskBlockedPayloadSchema,
  MissionTaskRetryRequestedPayload as ContractsMissionTaskRetryRequestedPayloadSchema,
  MissionTaskCancellationRequestedPayload as ContractsMissionTaskCancellationRequestedPayloadSchema,
  ManagedWorktreeRecordedPayload as ContractsManagedWorktreeRecordedPayloadSchema,
  ManagedWorktreeStatusUpdatedPayload as ContractsManagedWorktreeStatusUpdatedPayloadSchema,
  ManagedWorktreeRemovalRequestedPayload as ContractsManagedWorktreeRemovalRequestedPayloadSchema,
  AgentHandoffCreatedPayload as ContractsAgentHandoffCreatedPayloadSchema,
  AgentHandoffReconciledPayload as ContractsAgentHandoffReconciledPayloadSchema,
  MissionSchedulerLifecyclePayload as ContractsMissionSchedulerLifecyclePayloadSchema,
  MissionSchedulerConcurrencyLimitedPayload as ContractsMissionSchedulerConcurrencyLimitedPayloadSchema,
  MissionIntegrationLifecyclePayload as ContractsMissionIntegrationLifecyclePayloadSchema,
  VerificationRunLifecyclePayload as ContractsVerificationRunLifecyclePayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadSettledPayload = ContractsThreadSettledPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadUnsettledPayload = ContractsThreadUnsettledPayloadSchema;
export const ThreadSnoozedPayload = ContractsThreadSnoozedPayloadSchema;
export const ThreadUnsnoozedPayload = ContractsThreadUnsnoozedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;

export const MissionCreatedPayload = ContractsMissionCreatedPayloadSchema;
export const MissionUpdatedPayload = ContractsMissionUpdatedPayloadSchema;
export const MissionStartedPayload = ContractsMissionStartedPayloadSchema;
export const MissionCancellationRequestedPayload =
  ContractsMissionCancellationRequestedPayloadSchema;
export const MissionCancelledPayload = ContractsMissionCancelledPayloadSchema;
export const MissionCompletedPayload = ContractsMissionCompletedPayloadSchema;
export const MissionFailedPayload = ContractsMissionFailedPayloadSchema;
export const MissionRecoveryBlockedPayload = ContractsMissionRecoveryBlockedPayloadSchema;
export const MissionTaskCreatedPayload = ContractsMissionTaskCreatedPayloadSchema;
export const MissionTaskUpdatedPayload = ContractsMissionTaskUpdatedPayloadSchema;
export const MissionTaskLifecyclePayload = ContractsMissionTaskLifecyclePayloadSchema;
export const AgentRunStartedPayload = ContractsAgentRunStartedPayloadSchema;
export const AgentRunLifecyclePayload = ContractsAgentRunLifecyclePayloadSchema;
export const MissionTeamConfiguredPayload = ContractsMissionTeamConfiguredPayloadSchema;
export const MissionAgentUpsertedPayload = ContractsMissionAgentUpsertedPayloadSchema;
export const MissionAgentRemovedPayload = ContractsMissionAgentRemovedPayloadSchema;
export const MissionAgentPermissionsUpdatedPayload =
  ContractsMissionAgentPermissionsUpdatedPayloadSchema;
export const MissionTaskDependencyAddedPayload = ContractsMissionTaskDependencyAddedPayloadSchema;
export const MissionTaskDependencyRemovedPayload =
  ContractsMissionTaskDependencyRemovedPayloadSchema;
export const MissionTaskReadyPayload = ContractsMissionTaskReadyPayloadSchema;
export const MissionTaskBlockedPayload = ContractsMissionTaskBlockedPayloadSchema;
export const MissionTaskRetryRequestedPayload = ContractsMissionTaskRetryRequestedPayloadSchema;
export const MissionTaskCancellationRequestedPayload =
  ContractsMissionTaskCancellationRequestedPayloadSchema;
export const ManagedWorktreeRecordedPayload = ContractsManagedWorktreeRecordedPayloadSchema;
export const ManagedWorktreeStatusUpdatedPayload =
  ContractsManagedWorktreeStatusUpdatedPayloadSchema;
export const ManagedWorktreeRemovalRequestedPayload =
  ContractsManagedWorktreeRemovalRequestedPayloadSchema;
export const AgentHandoffCreatedPayload = ContractsAgentHandoffCreatedPayloadSchema;
export const AgentHandoffReconciledPayload = ContractsAgentHandoffReconciledPayloadSchema;
export const MissionSchedulerLifecyclePayload = ContractsMissionSchedulerLifecyclePayloadSchema;
export const MissionSchedulerConcurrencyLimitedPayload =
  ContractsMissionSchedulerConcurrencyLimitedPayloadSchema;
export const MissionIntegrationLifecyclePayload = ContractsMissionIntegrationLifecyclePayloadSchema;
export const VerificationRunLifecyclePayload = ContractsVerificationRunLifecyclePayloadSchema;
